version: "3.9"

volumes:
  mysql_data:

networks:
  realworld-network:
    driver: bridge

services:
  realworld-mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3308:3306"
    networks:
      - realworld-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  realworld-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/app.jar
    restart: unless-stopped
    environment:
      SPRING_PROFILE: "dev"
      DB_HOST: realworld-mysql
      TOKEN_SECRET: "thisIsNotAStrongSecretAlsoHardCodingASecretInADockerComposeFileIsNotRecommended"
    ports:
      - "8080:8080"
    networks:
      - realworld-network
    depends_on:
      realworld-mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - realworld-network
    depends_on:
      realworld-api:
        condition: service_healthy