version: "3.9"

volumes:
  mysql_data:

networks:
  realworld-network:
    driver: bridge

services:
  realworld-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3308:3306"
    networks:
      - realworld-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysql", "-uroot", "-proot", "-e", "SHOW DATABASES;" ]
      interval: 2s
      timeout: 2s
      retries: 15

  realworld-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/app.jar
    environment:
      SPRING_PROFILE: "dev"
      DB_HOST: realworld-mysql
      TOKEN_SECRET: "thisIsNotAStrongSecretAlsoHardCodingASecretInADockerComposeFileIsNotRecommended"
    ports:
      - "8080:8080"
    networks:
      - realworld-network
    depends_on:
      realworld-mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/tags" ]
      interval: 2s
      timeout: 2s
      retries: 15

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        API_URL: http://realworld-api:8080
    ports:
      - "3000:80"
    networks:
      - realworld-network
    depends_on:
      realworld-api:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 2s
      timeout: 2s
      retries: 15
