version: "3.9"

services:
  realworld-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - realworld-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  realworld-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/app.jar
    environment:
      SPRING_PROFILE: ci
      DB_HOST: realworld-mysql
      TOKEN_SECRET: thisIsNotAStrongSecretAlsoHardCodingASecretInADockerComposeFileIsNotRecommended
    networks:
      - realworld-network
    depends_on:
      realworld-mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - realworld-network
    depends_on:
      realworld-api:
        condition: service_healthy

networks:
  realworld-network:
    driver: bridge
