name: Run Selenium Tests

on:
  push:
    paths:
      - 'backend/**'
      - 'frontend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'backend/**'
      - 'frontend/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose-ci.yml

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env for compose
        run: echo "OWNER=${{ github.repository_owner }}" > .env

      - name: Pull images from GHCR
        run: docker compose pull

      - name: Start application
        run: docker compose up -d --wait

      - name: Check docker status
        if: always()
        run: docker compose ps

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('ui-tests/pom.xml') }}

      - name: Run Selenium tests
        working-directory: ui-tests
        run: mvn clean test -Dheadless=true -Dallure.results.directory=target/allure-results

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ui-tests/target/allure-results/

      - name: Stop and clean up containers
        if: always()
        run: docker compose down -v

  build-report:
    runs-on: ubuntu-latest
    if: always()
    needs: selenium-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean old allure-results
        run: rm -rf allure-results

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-results/

      - name: Build Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results/
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy Allure Report to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report